### ISSUE TITLE
Feedback for week 5

### ISSUE THREAD

**Issue by wistoft** [ZeeshanHaider2/JavaScript#1]
Overall a good handin. Keep up the good work.

## 1.1

Perfect.

## 1.2

Just right. A little thing to improve. The function should return the string. Not print it to the console.
 
## 1.7
correct.

## 1.8

I would have liked to see how you would explain it :-)
	
## 1.9

Good explanation.

	
# task 3

Good work. One thing I would like to improve is:
	
1. You use **class** attribute in your html. I think you should use **id** for everyone. Because there is only one search button,, for instance. You couldn't imagine having two buttons like this.

**Comment by ZeeshanHaider2** [comment]
Thanks for the useful feedback, Wistoft.
